### ISSUE TITLE
.txt to .docx conversion

### ISSUE THREAD

**Issue by mijalche** [davepwsmith/zotpick-applescript#1]
Dave, thanks for the apple script and the explanation for how to use scrivener, zotero, pandoc and marked2. 
It works very well. 
I always face one problem, for which I think that if we solved it will help a lot, especially for the writers with no IT/ programming knowledge. 
Is it possible to have a GUI app that will execute the pandoc command but it will give you an option to select the style (maybe dropdown option) and select the input (.txt) file and output (.docx) file. 
Thanks!

**Comment by davepwsmith** [comment]
There's plenty to go at on the [pandoc extras wiki](https://github.com/jgm/pandoc/wiki/Pandoc-Extras). [PanConvert](http://panconvert.sourceforge.net/) seems to fit the bill. It's really not very hard to run the terminal command though, and the instructions are all there!
Asking someone to write a completely different programme is not really what the issues section of a github repository is for, as @retorquere tried to point out to you in zotplus/zotero-better-bibtex#263

**Comment by davepwsmith** [comment]
I'm closing this since it really has nothing to do with my scripts...

**Comment by retorquere** [comment]
This is a bit of a rant; please accept my half-hearted apology in advance.

But L&L should really just get off their behind and implement this long-overdue enhancement themselves.

There's very little reason for them to do so of course -- I think they correctly sense that there's not any _real_ competition in their field, as they seem to be the benchmark that other solutions are measured against. Innovation costs, and, let's be honest, is not entirely likely to open any substantial new market for them. They can afford to stagnate, and stagnate they did. The only real change I've seen from them in recent memory is the release of a Windows version (although that has stagnated on version 1), but then, that _is_ a new market, and a possibly big one at that.

Given that L&L won't even expend the effort to make it feasible for others to innovate on their behalf (no extension points of any kind), it is my personal opinion that if volunteers do any substantial programming, it is best spent improving currently lesser offerings (such as Leo editor, or the Atom editor) to becoming a true match for Scrivener. Which is, in all honesty, the sole reason I've installed Scrivener-for-Linux; just as a way to find out what functions could (at some mythical time in the future when I have spare time) be interesting to pilfer and replicate.

I appreciate some of the things that Scrivener gets right, and I have indeed not found anything except org-mode that comes even close (but: emacs), but there are things that Scrivener gets very, very wrong. 

No extension points is one.

The other is the way it stores its documents, which is clearly stuck in a technological paradigm that was entirely relevant 10 years ago; where users have access to exactly one computer where they do everything, and backups are an occasional thing. Today's user, in contrast, has access to a multitude of devices, ranging from mobile and tablets (quicky notes and brainfarts), desktops,  laptops, and loaner-systems (for that brilliant insight while you pretend to listen to the great story of your uncle's summer holiday involving a drunken night on the pyramid of Giza he's already repeated you a gazillion times) where you log in via the web, and backups are automated and continuous. Scrivener even explicitly states that if you put your stuff in Dropbox, "you must be sure that it is fully synced before opening", but offers no indication in Scrivener that it is still syncing, and no explanation how to recover if you did open a partially-synced project. Scrivener could implement safe direct-to-dropbox sync (not trivially though given their architecture), but that would be work, and again, no new market, so no incentive, 

Git could ameliorate some of these issues, as it solves the "fully synced?" issue, but since Scriveners storage format consists of binary blobs (RTF) strewn around a directory, there shall be no merge, and as noted above, dropbox is risky because it will sensibly duplicate files if changed on both ends, but as Scrivener projects are not single files but loosely-connected files in a directory, you're up the creek trying to resolve the mess.

Rant out.

**Comment by davepwsmith** [comment]
Rant away, now that it's closed!

I (sort of) agree, and if I had the chops I would contribute (to Atom, probably) but I don't, so I'm stuck with hacking around scrivener with my _very_ limited abilities. Atom is a great editor, if a little slow, but it's miles off scrivener if you really get into what scrivener can do.

That being said, pretty much the only thing which is stopping me from using Atom for everything is the lack of an equivalent to Scrivener's "composite" view, where I can view and edit several text files in one buffer (pane?), one after the other with dividers in between. I haven't looked into how possible this would be, but I'm guessing it would be. 

As a sidenote, I was under the impression that Atom wasn't actually FOSS, but I might be wrong!

**Comment by retorquere** [comment]
Atom is fully open source, including the technologies it depends on, but at
this moment it's more interesting for what it can become than what it is.

I am unworried about its performance. Atom is young, and it's a well-known
pitfall to optimize early - the (often unheeded) truism is: first, get it
to work. Then, get it to work well. Only then, get it to work fast.
Javascript was at one time considered to be too slow for serious work, but
firefox is written in it for a large part; there's not much to javascript
that makes it _inherently_ slow, and has made enormous strides in the past
few years.
