### ISSUE TITLE
Work with any app?

### ISSUE THREAD

**Issue by Jmuccigr** [davepwsmith/zotpick-applescript#4]
@davepwsmith - I just discovered these handy scripts, but I don't work with Scrivener. Looking at them, I realized that it would be fairly easy to adapt them to work with whatever app is open. I forked the project, and made that change to the pandoc one as a test case. You can see [the changes](https://github.com/Jmuccigr/zotpick-applescript). I tested the new version in Scrivener, BBEdit, MacDown and TextEdit.

If you think this is an improvement, I can modify the others similarly and do a PR. Let me know.

**Comment by davepwsmith** [comment]
Hi, and thanks for this. There was a reason, originally, that I didn't do this - or I tried and failed, not able to get the frontmost application reliably. However there have been several updates to osx since then and it may be more reliable now, or you may have found a better solution than I did in the script. If you have tested it and it works every time, I would love you to make the change to all three scripts and submit a pull request. I no longer have a Mac, so am unable to test this myself!

**Comment by Jmuccigr** [comment]
OK, will do.

I've had some trouble myself with that same thing, and I had to modify your script where it checks that the app is frontmost. Not sure what changed.

**Comment by davepwsmith** [comment]
PR Accepted

**Comment by davepwsmith** [comment]
@Jmuccigr I'm sure that like I did, you moved on to other stuff since I handed this over to you, but it popped up again in a notification and I had a thought on 62f3d7de19dc0390b27ec3ad31bacbdf9eee4f39 and the desired behaviour of being able to use any app. If the problem is that the script gets picked as front-most, could you not just add a step which sends the script to the back before detecting front-most application? I will submit a PR for you to test if you like!

**Comment by Jmuccigr** [comment]
Got some specifics on this? I'm still not on Sierra, so that might be it.

**Comment by davepwsmith** [comment]
No - I don't even use a mac any more, just was looking back and struck by the thought. I would have thought that you would be able to do something like:

````
tell application "System Events" to set visible of process me to false
````
or 
````
tell application "System Events" to set visible of me to false
````
before you detect frontmost application? Just a thought, you will have to test it yourself I'm afraid!

**Comment by Jmuccigr** [comment]
If it ain't broke...
